"""
Django migration operations for TimescaleDB policies.

These operations are automatically generated by Django's migration system
when TimescaleDB policies are defined in model classes.
"""
from django.db.migrations.operations.base import Operation
from typing import Optional, Union, List, Dict, Any
from datetime import datetime, timedelta


class ApplyTimescalePolicies(Operation):
    """
    Apply TimescaleDB policies to a model.

    This operation is automatically generated when policies are defined
    in a model's TimescalePolicies class.
    """

    def __init__(
        self,
        model_name: str,
        compression_settings: Optional[Dict[str, Any]] = None,
        compression_policy: Optional[Dict[str, Any]] = None,
        retention_policy: Optional[Dict[str, Any]] = None,
        **kwargs
    ):
        """
        Initialize the ApplyTimescalePolicies operation.

        Args:
            model_name: The name of the model to apply policies to
            compression_settings: Compression configuration
            compression_policy: Compression policy configuration
            retention_policy: Retention policy configuration
        """
        self.model_name = model_name
        self.compression_settings = compression_settings
        self.compression_policy = compression_policy
        self.retention_policy = retention_policy
        super().__init__(**kwargs)

    def state_forwards(self, app_label, state):
        """
        The ApplyTimescalePolicies operation doesn't alter the model state.
        """
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """
        Apply the TimescaleDB policies to the database.
        """
        # Get the actual model class, not the migration state model
        from django.apps import apps
        model = apps.get_model(app_label, self.model_name)

        # Apply compression settings
        if self.compression_settings and self.compression_settings.get('enabled', False):
            model.timescale.enable_compression(
                compress_orderby=self.compression_settings.get('compress_orderby', []),
                compress_segmentby=self.compression_settings.get('compress_segmentby', []),
                compress_chunk_time_interval=self.compression_settings.get('compress_chunk_time_interval'),
                if_not_exists=True
            )

        # Apply compression policy
        if self.compression_policy:
            model.timescale.add_compression_policy(
                compress_after=self.compression_policy['compress_after'],
                schedule_interval=self.compression_policy.get('schedule_interval'),
                if_not_exists=True,
                compress_created_before=self.compression_policy.get('compress_created_before'),
                initial_start=self.compression_policy.get('initial_start'),
                timezone=self.compression_policy.get('timezone')
            )

        # Apply retention policy
        if self.retention_policy:
            model.timescale.add_retention_policy(
                drop_after=self.retention_policy['drop_after'],
                schedule_interval=self.retention_policy.get('schedule_interval'),
                if_not_exists=True,
                drop_created_before=self.retention_policy.get('drop_created_before'),
                initial_start=self.retention_policy.get('initial_start'),
                timezone=self.retention_policy.get('timezone')
            )

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        """
        Remove the TimescaleDB policies from the database.
        """
        # Get the actual model class, not the migration state model
        from django.apps import apps
        model = apps.get_model(app_label, self.model_name)

        # Remove policies (order matters - remove policies before disabling compression)
        if self.compression_policy:
            model.timescale.remove_compression_policy(if_exists=True)

        if self.retention_policy:
            model.timescale.remove_retention_policy(if_exists=True)

        # Note: We don't disable compression in reverse because TimescaleDB
        # doesn't support disabling compression once enabled

    def describe(self):
        """
        Return a human-readable description of the operation.
        """
        policies = []
        if self.compression_settings:
            policies.append("compression")
        if self.compression_policy:
            policies.append("compression policy")
        if self.retention_policy:
            policies.append("retention policy")

        policy_str = ", ".join(policies)
        return f"Apply TimescaleDB {policy_str} to {self.model_name}"

    @property
    def migration_name_fragment(self):
        """
        Return a fragment for the migration filename.
        """
        return f"apply_timescale_policies_{self.model_name.lower()}"

    def deconstruct(self):
        """
        Return a 3-tuple of class import path, positional args, and keyword args.
        """
        kwargs = {
            'model_name': self.model_name,
        }

        if self.compression_settings:
            kwargs['compression_settings'] = self.compression_settings
        if self.compression_policy:
            kwargs['compression_policy'] = self.compression_policy
        if self.retention_policy:
            kwargs['retention_policy'] = self.retention_policy

        return (
            self.__class__.__qualname__,
            [],
            kwargs
        )


class RemoveTimescalePolicies(Operation):
    """
    Remove TimescaleDB policies from a model.

    This operation is automatically generated when policies are removed
    from a model's TimescalePolicies class.
    """

    def __init__(
        self,
        model_name: str,
        remove_compression_policy: bool = False,
        remove_retention_policy: bool = False,
        **kwargs
    ):
        """
        Initialize the RemoveTimescalePolicies operation.

        Args:
            model_name: The name of the model to remove policies from
            remove_compression_policy: Whether to remove compression policy
            remove_retention_policy: Whether to remove retention policy
        """
        self.model_name = model_name
        self.remove_compression_policy = remove_compression_policy
        self.remove_retention_policy = remove_retention_policy
        super().__init__(**kwargs)

    def state_forwards(self, app_label, state):
        """
        The RemoveTimescalePolicies operation doesn't alter the model state.
        """
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """
        Remove the TimescaleDB policies from the database.
        """
        # Get the actual model class, not the migration state model
        from django.apps import apps
        model = apps.get_model(app_label, self.model_name)

        if self.remove_compression_policy:
            model.timescale.remove_compression_policy(if_exists=True)

        if self.remove_retention_policy:
            model.timescale.remove_retention_policy(if_exists=True)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        """
        This operation is not reversible without the original policy definitions.
        """
        raise NotImplementedError(
            "RemoveTimescalePolicies is not reversible. "
            "The original policy definitions would be needed to reverse this operation."
        )

    def describe(self):
        """
        Return a human-readable description of the operation.
        """
        policies = []
        if self.remove_compression_policy:
            policies.append("compression policy")
        if self.remove_retention_policy:
            policies.append("retention policy")

        policy_str = ", ".join(policies)
        return f"Remove TimescaleDB {policy_str} from {self.model_name}"

    @property
    def migration_name_fragment(self):
        """
        Return a fragment for the migration filename.
        """
        return f"remove_timescale_policies_{self.model_name.lower()}"

    def deconstruct(self):
        """
        Return a 3-tuple of class import path, positional args, and keyword args.
        """
        kwargs = {
            'model_name': self.model_name,
        }

        if self.remove_compression_policy:
            kwargs['remove_compression_policy'] = self.remove_compression_policy
        if self.remove_retention_policy:
            kwargs['remove_retention_policy'] = self.remove_retention_policy

        return (
            self.__class__.__qualname__,
            [],
            kwargs
        )
